#define FIREDANCER_MAJOR_VERSION 0
#define FIREDANCER_MINOR_VERSION 1
#define FIREDANCER_PATCH_VERSION 1
#define FIREDANCER_VERSION "0.1.1"
#define FIREDANCER_COMMIT_REF_CSTR "a1add6ed48faed7453cba41fe9ecaad21d0ab9de"
#define FIREDANCER_COMMIT_REF_U32 0xa1add6ed
